# Generated by Django 3.2 on 2022-11-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/customer/lazy.png', null=True, upload_to='profile_pic/customer'),
        ),
    ]
